spring:
  application:
    name: OpenNet
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb
    username: taskuser
    password: taskpass
  redis:
    host: localhost
    port: 6379

rocketmq:
  name-server: localhost:9876
  producer:
    group: notification_producer_group
